# Generated by xtables-save v1.8.2 on Tue Mar 21 00:38:35 2023
*raw
:PREROUTING ACCEPT [54752:66248002]
:OUTPUT ACCEPT [61484:16390370]
COMMIT
# Completed on Tue Mar 21 00:38:35 2023
# Generated by xtables-save v1.8.2 on Tue Mar 21 00:38:35 2023
*mangle
:PREROUTING ACCEPT [54752:66248002]
:INPUT ACCEPT [46711:64930860]
:FORWARD ACCEPT [5247:1130539]
:OUTPUT ACCEPT [61484:16390370]
:POSTROUTING ACCEPT [66731:17513655]
COMMIT
# Completed on Tue Mar 21 00:38:35 2023
# Generated by xtables-save v1.8.2 on Tue Mar 21 00:38:35 2023
*nat
:PREROUTING ACCEPT [3025:208833]
:INPUT ACCEPT [4:208]
:POSTROUTING ACCEPT [12762:771394]
:OUTPUT ACCEPT [12541:756932]
COMMIT
# Completed on Tue Mar 21 00:38:35 2023
# Generated by xtables-save v1.8.2 on Tue Mar 21 00:38:35 2023
*security
:INPUT ACCEPT [46711:64930860]
:FORWARD ACCEPT [5241:1122979]
:OUTPUT ACCEPT [545:68626]
-A OUTPUT -d 168.63.129.16/32 -p tcp -m tcp --dport 53 -j ACCEPT
-A OUTPUT -d 168.63.129.16/32 -p tcp -m owner --uid-owner 0 -j ACCEPT
-A OUTPUT -d 168.63.129.16/32 -p tcp -m conntrack --ctstate INVALID,NEW -j DROP
COMMIT
# Completed on Tue Mar 21 00:38:35 2023
# Generated by xtables-save v1.8.2 on Tue Mar 21 00:38:35 2023
*filter
:INPUT ACCEPT [327:28962]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 10.56.177.0/24 -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A FORWARD -s 10.56.177.0/24 -d 172.17.89.32/27 -p tcp -m tcp --dport 22 -j ACCEPT
-A FORWARD -s 172.17.89.32/27 -d 10.56.177.0/24 -p tcp -m tcp --sport 22 -j ACCEPT
-A FORWARD -s 10.56.177.0/24 -d 172.17.89.32/27 -p tcp -m tcp --dport 3389 -j ACCEPT
-A FORWARD -s 172.17.89.32/27 -d 10.56.177.0/24 -p tcp -m tcp --sport 3389 -j ACCEPT
-A FORWARD -d 172.17.89.36/32 -p tcp -m tcp --dport 53 -j ACCEPT
-A FORWARD -s 172.17.89.36/32 -p tcp -m tcp --sport 53 -j ACCEPT
-A FORWARD -d 172.17.89.36/32 -p udp -m udp --dport 53 -j ACCEPT
-A FORWARD -s 172.17.89.36/32 -p udp -m udp --sport 53 -j ACCEPT
-A FORWARD -s 10.56.177.0/24 -d 172.17.89.37/32 -p tcp -m tcp --dport 3306 -j ACCEPT
-A FORWARD -s 172.17.89.37/32 -d 10.56.177.0/24 -p tcp -m tcp --sport 3306 -j ACCEPT
-A FORWARD -s 10.56.177.0/24 -d 172.17.89.37/32 -p tcp -m tcp --dport 80 -j ACCEPT
-A FORWARD -s 172.17.89.37/32 -d 10.56.177.0/24 -p tcp -m tcp --sport 80 -j ACCEPT
-A FORWARD -s 10.56.177.0/24 -d 172.17.89.36/32 -p tcp -m tcp --dport 80 -j ACCEPT
-A FORWARD -s 172.17.89.36/32 -d 10.56.177.0/24 -p tcp -m tcp --sport 80 -j ACCEPT
-A FORWARD -s 10.56.177.0/24 -d 172.17.89.36/32 -p tcp -m tcp --dport 21 -j ACCEPT
-A FORWARD -s 172.17.89.36/32 -d 10.56.177.0/24 -p tcp -m tcp --sport 21 -j ACCEPT
-A FORWARD -s 10.56.177.0/24 -d 172.17.89.36/32 -p tcp -m tcp --dport 50000:51000 -j ACCEPT
-A FORWARD -s 172.17.89.36/32 -d 10.56.177.0/24 -p tcp -m tcp --sport 50000:51000 -j ACCEPT
-A FORWARD -j LOG --log-prefix TO_DROP_FORWARD
-A FORWARD -j DROP
-A OUTPUT -j ACCEPT
COMMIT
# Completed on Tue Mar 21 00:38:35 2023


































